[package]
name = "yarvk_examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yarvk = { path = "../yarvk"}
winit = "0.28.0"
image = "0.23"
rayon = "1.5.3"
raw-window-handle = "0.5.0"